# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.27
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
enable_checklog_odoo: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env:
    PIP_INDEX_URL: https://pypi.org/simple/
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 17.0
org_name: Sygel, Odoo Community Association (OCA)
org_slug: sygel-technology
rebel_module_groups: []
repo_description: This project is a collection of Odoo modules containing various
    data files that are too big to fit the official addons or the other Community
    projects.
repo_name: sy-community-data-files
repo_slug: sy-community-data-files
repo_website: https://github.com/sygel-technology/sy-community-data-files
use_pyproject_toml: true
use_ruff: true

